# Generated by Django 6.0.3 on 2026-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('synopsis', models.TextField(blank=True)),
                ('prix_location', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre_exemplaires', models.IntegerField(default=1)),
                ('est_disponible', models.BooleanField(default=True)),
                ('date_sortie', models.DateField()),
            ],
        ),
    ]
