# Generated by Django 6.0.3 on 2026-04-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='code_reference',
            field=models.CharField(default='FILM000001', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
