# Generated by Django 6.0.3 on 2026-04-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0002_film_code_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='code_reference',
            field=models.CharField(default='DEFAULT123', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
