# Generated by Django 6.0.3 on 2026-04-23 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0003_alter_film_code_reference_alter_film_date_sortie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('biographie', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='realisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cataloge.realisateur'),
        ),
    ]
